language: cpp
sudo: false
addons:
  apt:
    packages:
      - python3
      - libftdi-dev

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew install python3;
      fi

matrix:
  include:
    - compiler: clang
    #- compiler: gcc
    - os: osx
      compiler: clang

script: make
notifications:
  email: false
